# Generated by Django 3.2.9 on 2021-12-13 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=9, max_digits=16)),
                ('date_purchased', models.DateField()),
                ('price_purchased', models.DecimalField(decimal_places=2, max_digits=16)),
                ('closed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20)),
                ('amount_sold', models.DecimalField(decimal_places=9, max_digits=16)),
                ('date_sold', models.DateField()),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=16)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cryptfolio_app.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
