# Generated by Django 3.2.9 on 2021-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldasset',
            name='price_purchased',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=16),
            preserve_default=False,
        ),
    ]
