# Generated by Django 3.2.9 on 2021-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptfolio_app', '0002_soldasset_price_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
